/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'status' : ArticleStatus,
  'coverImageUrl' : [] | [ExternalBlob],
  'title' : string,
  'inlineImages' : Array<ExternalBlob>,
  'imageUrls' : Array<string>,
  'body' : ArticleBody,
  'slug' : string,
  'publishedAt' : [] | [Time],
  'author' : string,
  'updatedAt' : Time,
  'seoKeywords' : Array<string>,
}
export interface ArticleBody {
  'rawHtml' : string,
  'blocks' : Array<Block>,
  'attachments' : Array<Attachment>,
}
export type ArticleStatus = { 'published' : null } |
  { 'draft' : null };
export interface Attachment {
  'url' : string,
  'size' : bigint,
  'type' : string,
  'caption' : [] | [string],
}
export interface Block {
  'content' : string,
  'metadata' : [] | [Metadata],
  'layout' : [] | [Layout],
  'style' : Style,
}
export type ExternalBlob = Uint8Array;
export interface Layout {
  'padding' : [] | [bigint],
  'alignment' : [] | [string],
  'columns' : [] | [bigint],
}
export interface Metadata {
  'tag' : [] | [string],
  'attributes' : [] | [string],
}
export interface Style {
  'background' : [] | [string],
  'color' : [] | [string],
  'fontWeight' : [] | [string],
  'fontSize' : [] | [bigint],
}
export type Time = bigint;
export interface UserProfile {
  'bio' : [] | [string],
  'name' : string,
  'avatarUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArticle' : ActorMethod<
    [
      string,
      string,
      ArticleBody,
      [] | [ExternalBlob],
      Array<string>,
      Array<string>,
      string,
      Array<ExternalBlob>,
    ],
    bigint
  >,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'getArticleById' : ActorMethod<[bigint], [] | [Article]>,
  'getArticleBySlug' : ActorMethod<[string], [] | [Article]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHeroImage' : ActorMethod<[], string>,
  'getLatestArticles' : ActorMethod<[bigint], Array<Article>>,
  'getPublishedArticles' : ActorMethod<[bigint, bigint], Array<Article>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerFirstAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchArticles' : ActorMethod<[string], Array<Article>>,
  'togglePublishArticle' : ActorMethod<[bigint, ArticleStatus], undefined>,
  'updateArticle' : ActorMethod<
    [
      bigint,
      string,
      string,
      ArticleBody,
      [] | [ExternalBlob],
      Array<string>,
      Array<string>,
      string,
      Array<ExternalBlob>,
    ],
    undefined
  >,
  'updateHeroImage' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];