/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Metadata = IDL.Record({
  'tag' : IDL.Opt(IDL.Text),
  'attributes' : IDL.Opt(IDL.Text),
});
export const Layout = IDL.Record({
  'padding' : IDL.Opt(IDL.Nat),
  'alignment' : IDL.Opt(IDL.Text),
  'columns' : IDL.Opt(IDL.Nat),
});
export const Style = IDL.Record({
  'background' : IDL.Opt(IDL.Text),
  'color' : IDL.Opt(IDL.Text),
  'fontWeight' : IDL.Opt(IDL.Text),
  'fontSize' : IDL.Opt(IDL.Nat),
});
export const Block = IDL.Record({
  'content' : IDL.Text,
  'metadata' : IDL.Opt(Metadata),
  'layout' : IDL.Opt(Layout),
  'style' : Style,
});
export const Attachment = IDL.Record({
  'url' : IDL.Text,
  'size' : IDL.Nat,
  'type' : IDL.Text,
  'caption' : IDL.Opt(IDL.Text),
});
export const ArticleBody = IDL.Record({
  'rawHtml' : IDL.Text,
  'blocks' : IDL.Vec(Block),
  'attachments' : IDL.Vec(Attachment),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ArticleStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const Time = IDL.Int;
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'status' : ArticleStatus,
  'coverImageUrl' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'inlineImages' : IDL.Vec(ExternalBlob),
  'imageUrls' : IDL.Vec(IDL.Text),
  'body' : ArticleBody,
  'slug' : IDL.Text,
  'publishedAt' : IDL.Opt(Time),
  'author' : IDL.Text,
  'updatedAt' : Time,
  'seoKeywords' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ArticleBody,
        IDL.Opt(ExternalBlob),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'getArticleById' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
  'getArticleBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHeroImage' : IDL.Func([], [IDL.Text], ['query']),
  'getLatestArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
  'getPublishedArticles' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Article)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'togglePublishArticle' : IDL.Func([IDL.Nat, ArticleStatus], [], []),
  'updateArticle' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        ArticleBody,
        IDL.Opt(ExternalBlob),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(ExternalBlob),
      ],
      [],
      [],
    ),
  'updateHeroImage' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Metadata = IDL.Record({
    'tag' : IDL.Opt(IDL.Text),
    'attributes' : IDL.Opt(IDL.Text),
  });
  const Layout = IDL.Record({
    'padding' : IDL.Opt(IDL.Nat),
    'alignment' : IDL.Opt(IDL.Text),
    'columns' : IDL.Opt(IDL.Nat),
  });
  const Style = IDL.Record({
    'background' : IDL.Opt(IDL.Text),
    'color' : IDL.Opt(IDL.Text),
    'fontWeight' : IDL.Opt(IDL.Text),
    'fontSize' : IDL.Opt(IDL.Nat),
  });
  const Block = IDL.Record({
    'content' : IDL.Text,
    'metadata' : IDL.Opt(Metadata),
    'layout' : IDL.Opt(Layout),
    'style' : Style,
  });
  const Attachment = IDL.Record({
    'url' : IDL.Text,
    'size' : IDL.Nat,
    'type' : IDL.Text,
    'caption' : IDL.Opt(IDL.Text),
  });
  const ArticleBody = IDL.Record({
    'rawHtml' : IDL.Text,
    'blocks' : IDL.Vec(Block),
    'attachments' : IDL.Vec(Attachment),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ArticleStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Time = IDL.Int;
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'status' : ArticleStatus,
    'coverImageUrl' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'inlineImages' : IDL.Vec(ExternalBlob),
    'imageUrls' : IDL.Vec(IDL.Text),
    'body' : ArticleBody,
    'slug' : IDL.Text,
    'publishedAt' : IDL.Opt(Time),
    'author' : IDL.Text,
    'updatedAt' : Time,
    'seoKeywords' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ArticleBody,
          IDL.Opt(ExternalBlob),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'getArticleById' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
    'getArticleBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Article)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHeroImage' : IDL.Func([], [IDL.Text], ['query']),
    'getLatestArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
    'getPublishedArticles' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
    'togglePublishArticle' : IDL.Func([IDL.Nat, ArticleStatus], [], []),
    'updateArticle' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          ArticleBody,
          IDL.Opt(ExternalBlob),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(ExternalBlob),
        ],
        [],
        [],
      ),
    'updateHeroImage' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };