/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Article {
    id: bigint;
    status: ArticleStatus;
    coverImageUrl?: ExternalBlob;
    title: string;
    inlineImages: Array<ExternalBlob>;
    imageUrls: Array<string>;
    body: ArticleBody;
    slug: string;
    publishedAt?: Time;
    author: string;
    updatedAt: Time;
    seoKeywords: Array<string>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ArticleBody {
    rawHtml: string;
    blocks: Array<Block>;
    attachments: Array<Attachment>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Metadata {
    tag?: string;
    attributes?: string;
}
export interface Attachment {
    url: string;
    size: bigint;
    type: string;
    caption?: string;
}
export interface Style {
    background?: string;
    color?: string;
    fontWeight?: string;
    fontSize?: bigint;
}
export interface Block {
    content: string;
    metadata?: Metadata;
    layout?: Layout;
    style: Style;
}
export interface Layout {
    padding?: bigint;
    alignment?: string;
    columns?: bigint;
}
export interface UserProfile {
    bio?: string;
    name: string;
    avatarUrl?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ArticleStatus {
    published = "published",
    draft = "draft"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createArticle(title: string, slug: string, body: ArticleBody, coverImageUrl: ExternalBlob | null, imageUrls: Array<string>, seoKeywords: Array<string>, author: string, inlineImages: Array<ExternalBlob>): Promise<bigint>;
    deleteArticle(id: bigint): Promise<void>;
    getArticleById(id: bigint): Promise<Article | null>;
    getArticleBySlug(slug: string): Promise<Article | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHeroImage(): Promise<string>;
    getLatestArticles(limit: bigint): Promise<Array<Article>>;
    getPublishedArticles(page: bigint, pageSize: bigint): Promise<Array<Article>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerFirstAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchArticles(keyword: string): Promise<Array<Article>>;
    togglePublishArticle(id: bigint, newStatus: ArticleStatus): Promise<void>;
    updateArticle(id: bigint, title: string, slug: string, body: ArticleBody, coverImageUrl: ExternalBlob | null, imageUrls: Array<string>, seoKeywords: Array<string>, author: string, inlineImages: Array<ExternalBlob>): Promise<void>;
    updateHeroImage(url: string): Promise<void>;
}
import type { Article as _Article, ArticleBody as _ArticleBody, ArticleStatus as _ArticleStatus, Attachment as _Attachment, Block as _Block, ExternalBlob as _ExternalBlob, Layout as _Layout, Metadata as _Metadata, Style as _Style, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createArticle(arg0: string, arg1: string, arg2: ArticleBody, arg3: ExternalBlob | null, arg4: Array<string>, arg5: Array<string>, arg6: string, arg7: Array<ExternalBlob>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(arg0, arg1, to_candid_ArticleBody_n10(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, await to_candid_vec_n26(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(arg0, arg1, to_candid_ArticleBody_n10(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, await to_candid_vec_n26(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async deleteArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(arg0);
            return result;
        }
    }
    async getArticleById(arg0: bigint): Promise<Article | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticleById(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticleById(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticleBySlug(arg0: string): Promise<Article | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticleBySlug(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticleBySlug(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHeroImage(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeroImage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeroImage();
            return result;
        }
    }
    async getLatestArticles(arg0: bigint): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestArticles(arg0);
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestArticles(arg0);
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedArticles(arg0: bigint, arg1: bigint): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedArticles(arg0, arg1);
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedArticles(arg0, arg1);
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerFirstAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFirstAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFirstAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchArticles(arg0: string): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchArticles(arg0);
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchArticles(arg0);
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async togglePublishArticle(arg0: bigint, arg1: ArticleStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePublishArticle(arg0, to_candid_ArticleStatus_n61(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePublishArticle(arg0, to_candid_ArticleStatus_n61(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateArticle(arg0: bigint, arg1: string, arg2: string, arg3: ArticleBody, arg4: ExternalBlob | null, arg5: Array<string>, arg6: Array<string>, arg7: string, arg8: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticle(arg0, arg1, arg2, to_candid_ArticleBody_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n24(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, await to_candid_vec_n26(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticle(arg0, arg1, arg2, to_candid_ArticleBody_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n24(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, await to_candid_vec_n26(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async updateHeroImage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHeroImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHeroImage(arg0);
            return result;
        }
    }
}
function from_candid_ArticleBody_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArticleBody): ArticleBody {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ArticleStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArticleStatus): ArticleStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_Article_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Promise<Article> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Attachment_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attachment): Attachment {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Block_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Block): Block {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Layout_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Layout): Layout {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Metadata_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Metadata): Metadata {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Style_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Style): Style {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Article]): Promise<Article | null> {
    return value.length === 0 ? null : await from_candid_Article_n28(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Metadata]): Metadata | null {
    return value.length === 0 ? null : from_candid_Metadata_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Layout]): Layout | null {
    return value.length === 0 ? null : from_candid_Layout_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n54(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ArticleStatus;
    coverImageUrl: [] | [_ExternalBlob];
    title: string;
    inlineImages: Array<_ExternalBlob>;
    imageUrls: Array<string>;
    body: _ArticleBody;
    slug: string;
    publishedAt: [] | [_Time];
    author: string;
    updatedAt: _Time;
    seoKeywords: Array<string>;
}): Promise<{
    id: bigint;
    status: ArticleStatus;
    coverImageUrl?: ExternalBlob;
    title: string;
    inlineImages: Array<ExternalBlob>;
    imageUrls: Array<string>;
    body: ArticleBody;
    slug: string;
    publishedAt?: Time;
    author: string;
    updatedAt: Time;
    seoKeywords: Array<string>;
}> {
    return {
        id: value.id,
        status: from_candid_ArticleStatus_n30(_uploadFile, _downloadFile, value.status),
        coverImageUrl: record_opt_to_undefined(await from_candid_opt_n32(_uploadFile, _downloadFile, value.coverImageUrl)),
        title: value.title,
        inlineImages: await from_candid_vec_n34(_uploadFile, _downloadFile, value.inlineImages),
        imageUrls: value.imageUrls,
        body: from_candid_ArticleBody_n35(_uploadFile, _downloadFile, value.body),
        slug: value.slug,
        publishedAt: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.publishedAt)),
        author: value.author,
        updatedAt: value.updatedAt,
        seoKeywords: value.seoKeywords
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rawHtml: string;
    blocks: Array<_Block>;
    attachments: Array<_Attachment>;
}): {
    rawHtml: string;
    blocks: Array<Block>;
    attachments: Array<Attachment>;
} {
    return {
        rawHtml: value.rawHtml,
        blocks: from_candid_vec_n37(_uploadFile, _downloadFile, value.blocks),
        attachments: from_candid_vec_n49(_uploadFile, _downloadFile, value.attachments)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    metadata: [] | [_Metadata];
    layout: [] | [_Layout];
    style: _Style;
}): {
    content: string;
    metadata?: Metadata;
    layout?: Layout;
    style: Style;
} {
    return {
        content: value.content,
        metadata: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.metadata)),
        layout: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.layout)),
        style: from_candid_Style_n47(_uploadFile, _downloadFile, value.style)
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tag: [] | [string];
    attributes: [] | [string];
}): {
    tag?: string;
    attributes?: string;
} {
    return {
        tag: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.tag)),
        attributes: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.attributes))
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    padding: [] | [bigint];
    alignment: [] | [string];
    columns: [] | [bigint];
}): {
    padding?: bigint;
    alignment?: string;
    columns?: bigint;
} {
    return {
        padding: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.padding)),
        alignment: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.alignment)),
        columns: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.columns))
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    background: [] | [string];
    color: [] | [string];
    fontWeight: [] | [string];
    fontSize: [] | [bigint];
}): {
    background?: string;
    color?: string;
    fontWeight?: string;
    fontSize?: bigint;
} {
    return {
        background: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.background)),
        color: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.color)),
        fontWeight: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.fontWeight)),
        fontSize: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.fontSize))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    size: bigint;
    type: string;
    caption: [] | [string];
}): {
    url: string;
    size: bigint;
    type: string;
    caption?: string;
} {
    return {
        url: value.url,
        size: value.size,
        type: value.type,
        caption: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.caption))
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    name: string;
    avatarUrl: [] | [string];
}): {
    bio?: string;
    name: string;
    avatarUrl?: string;
} {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.bio)),
        name: value.name,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.avatarUrl))
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
}): ArticleStatus {
    return "published" in value ? ArticleStatus.published : "draft" in value ? ArticleStatus.draft : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n33(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Block>): Array<Block> {
    return value.map((x)=>from_candid_Block_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attachment>): Array<Attachment> {
    return value.map((x)=>from_candid_Attachment_n50(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Promise<Array<Article>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Article_n28(_uploadFile, _downloadFile, x)));
}
function to_candid_ArticleBody_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleBody): _ArticleBody {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ArticleStatus_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleStatus): _ArticleStatus {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_Attachment_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Attachment): _Attachment {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_Block_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Block): _Block {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Layout_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Layout): _Layout {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Metadata_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Metadata): _Metadata {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Style_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Style): _Style {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rawHtml: string;
    blocks: Array<Block>;
    attachments: Array<Attachment>;
}): {
    rawHtml: string;
    blocks: Array<_Block>;
    attachments: Array<_Attachment>;
} {
    return {
        rawHtml: value.rawHtml,
        blocks: to_candid_vec_n12(_uploadFile, _downloadFile, value.blocks),
        attachments: to_candid_vec_n21(_uploadFile, _downloadFile, value.attachments)
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    metadata?: Metadata;
    layout?: Layout;
    style: Style;
}): {
    content: string;
    metadata: [] | [_Metadata];
    layout: [] | [_Layout];
    style: _Style;
} {
    return {
        content: value.content,
        metadata: value.metadata ? candid_some(to_candid_Metadata_n15(_uploadFile, _downloadFile, value.metadata)) : candid_none(),
        layout: value.layout ? candid_some(to_candid_Layout_n17(_uploadFile, _downloadFile, value.layout)) : candid_none(),
        style: to_candid_Style_n19(_uploadFile, _downloadFile, value.style)
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tag?: string;
    attributes?: string;
}): {
    tag: [] | [string];
    attributes: [] | [string];
} {
    return {
        tag: value.tag ? candid_some(value.tag) : candid_none(),
        attributes: value.attributes ? candid_some(value.attributes) : candid_none()
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    padding?: bigint;
    alignment?: string;
    columns?: bigint;
}): {
    padding: [] | [bigint];
    alignment: [] | [string];
    columns: [] | [bigint];
} {
    return {
        padding: value.padding ? candid_some(value.padding) : candid_none(),
        alignment: value.alignment ? candid_some(value.alignment) : candid_none(),
        columns: value.columns ? candid_some(value.columns) : candid_none()
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    background?: string;
    color?: string;
    fontWeight?: string;
    fontSize?: bigint;
}): {
    background: [] | [string];
    color: [] | [string];
    fontWeight: [] | [string];
    fontSize: [] | [bigint];
} {
    return {
        background: value.background ? candid_some(value.background) : candid_none(),
        color: value.color ? candid_some(value.color) : candid_none(),
        fontWeight: value.fontWeight ? candid_some(value.fontWeight) : candid_none(),
        fontSize: value.fontSize ? candid_some(value.fontSize) : candid_none()
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    size: bigint;
    type: string;
    caption?: string;
}): {
    url: string;
    size: bigint;
    type: string;
    caption: [] | [string];
} {
    return {
        url: value.url,
        size: value.size,
        type: value.type,
        caption: value.caption ? candid_some(value.caption) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    name: string;
    avatarUrl?: string;
}): {
    bio: [] | [string];
    name: string;
    avatarUrl: [] | [string];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        name: value.name,
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none()
    };
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleStatus): {
    published: null;
} | {
    draft: null;
} {
    return value == ArticleStatus.published ? {
        published: null
    } : value == ArticleStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Block>): Array<_Block> {
    return value.map((x)=>to_candid_Block_n13(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Attachment>): Array<_Attachment> {
    return value.map((x)=>to_candid_Attachment_n22(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n25(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
